# Generated by Django 3.1.3 on 2020-11-04 13:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField()),
                ('reported_location', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
